### PR TITLE
Fix context passthrough and bundling

### PR DESCRIPTION
**Pull request by sompylasar**
- Pass context to rendered components. https://github.com/sompylasar/atellier/commit/98357eda93f4e09b1a51beccee15e17880ef43f7
- Use common spelling of `ReactDOM`. https://github.com/sompylasar/atellier/commit/aa1c3a7d42b985534237e6f0f908155ae61dba05
- Use external `react` and `react-dom`. https://github.com/sompylasar/atellier/commit/034164ba1016eb342f000d3ca94dd301e4a9bf1b

### CODE REVIEW

**Comment by sompylasar** [comment]
Any chance for this PR getting merged and published to `npm`?

**Comment by agutoli** [comment]
I have tested it and It works well, tks for help us!

**Comment by sompylasar** [comment]
Yay!

**Comment by sompylasar** [comment]
@agutoli Hi, at which version is this published?

**Pull request merged**
